### ISSUE TITLE
Is this job still open?

### ISSUE THREAD

**Issue by azizramdan** [riandyrn/remindme-laravel#18]
I access the [submit form page](https://ghazlabs.com/nabitu/senior-backend-engineer-laravel.html) but the page is not found, is this job still open?

**Comment by riandyrn** [comment]
Hello, @azizramdan

Yeah, we decided to close the submission for now.

Have you finished your take-home challenge? I noticed you are still missing the unit tests in your repo.

If you already finish, you can fill out the submission form [here](https://docs.google.com/forms/d/e/1FAIpQLSfJnmuKZIfMPy2HRrE-RdB9bJKddE_aNRJRv6uD2ZRzKBz4YQ/viewform). I just opened it for you.

**Comment by azizramdan** [comment]
I've sent in my submission. Thanks a lot for the chance!
