### ISSUE TITLE
Submission CV Page error 404?

### ISSUE THREAD

**Issue by rifqifauzi** [riandyrn/remindme-laravel#19]
Apakah masih available?
saya mengunjungi halaman submission CV Page di link yang tersedia ternyata error 404,
Link halaman ini : https://ghazlabs.com/nabitu/senior-backend-engineer-laravel.html

Submit your CV in PDF along with the URL of your forked repository to [this page](https://ghazlabs.com/nabitu/senior-backend-engineer-laravel.html).

**Comment by riandyrn** [comment]
Hello, @rifqifauzi

We decided to close this vacancy. You can submit your submission using [this form](https://docs.google.com/forms/d/e/1FAIpQLSfJnmuKZIfMPy2HRrE-RdB9bJKddE_aNRJRv6uD2ZRzKBz4YQ/viewform).

I will leave it open until today.
