### ISSUE TITLE
Endpoint to retrieve active user

### ISSUE THREAD

**Issue by azizramdan** [riandyrn/remindme-laravel#6]
I usually need an endpoint to get the currently active user data, for example GET `/api/me`. The reason is because user data is not stored permanently on the client side to ensure it always gets the latest data. So when you refresh the browser will always call that endpoint. Is this necessary for this project?

**Comment by riandyrn** [comment]
Hello, @azizramdan

First of all, thanks for asking the question!

> ensure it always gets the latest data.

What do you mean by user latest data? Do you mean the user info like id, email, & name? Aren't they never updated? 🤔

**Comment by azizramdan** [comment]
That's right, user info like id, email, and name. In this project there is no user info update, I compared it with the real project, so I want to confirm whether this flow is needed or not in this case.

**Comment by riandyrn** [comment]
>  I compared it with the real project, so I want to confirm whether this flow is needed or not in this case.

Hmm.., ok, rather than real project, try to think it as MVP (Minimum Viable Product), @azizramdan.

In MVP, we just need to build features that satisfy business needs. So if you think having this endpoint is needed from the business perspective, just go for it. 😁👍

**Comment by azizramdan** [comment]
Okay noted, thanks for answering.
