### ISSUE TITLE
Questions Regarding Implementation of an Email Notification System for the /api/reminders Endpoint

### ISSUE THREAD

**Issue by rurifaqih15** [riandyrn/remindme-laravel#8]
Hello @riandyrn
```
POST: /api/reminders

This endpoint is used by client to create a new reminder. When the reminder is successfully created, the system will send email notification to the user when the reminder is due (when reminder_at is reached).
```

for this point,  does the system for sending email notifications also need to be worked on?

Thanks

**Comment by riandyrn** [comment]
Hello, @rurifaqih15

Thanks for asking the question.

> does the system for sending email notifications also need to be worked on?

Yes, your web app needs to be able to send an email notification.

However, please remember that it only needs to be able to send email locally, so you don't need to set up a public SMTP server. You can use something like [mailpit](https://github.com/axllent/mailpit).

**Comment by rurifaqih15** [comment]
Okay.
Thanks for answer
